export enum AppMutationTypes {
  TOGGLE_DOCKED_NAV = 'TOGGLE_DOCKED_NAV',
  SET_DOCKED_NAV_STATE = 'SET_DOCKED_NAV_STATE',
  TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR',
  CLOSE_SIDEBAR = 'CLOSE_SIDEBAR',
  TOGGLE_DEVICE = 'TOGGLE_DEVICE',
  SET_LANGUAGE = 'SET_LANGUAGE',
  SET_SIZE = 'SET_SIZE',
}
